version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
      - mongodb
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      REDIS_PASSWORD: myredispassword
      MONGODB_USERNAME: mymongodbuser
      MONGODB_PASSWORD: mymongodbpassword
      MONGODB_DATABASE: mymongodb
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: myredispassword
    volumes:
      - ./redis-data:/data
    restart: always

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mymongodbrpassword
    volumes:
      - ./mongo-data:/data/db
    restart: always